### ISSUE TITLE
Rename => Request failed

### ISSUE THREAD

**Issue by snapgt** [sjarvela/kloudspeaker#140] opened 2016-05-31 07:26 UTC
To recreate issue:
1.  Right-click on a folder.
2.  Select "Rename" from the menu.
3.  Enter a new name.
4.  Click Rename.
   Immediately after clicking Rename, the pop up error titled "kloudspeaker" with the text "Request failed" will appear.  This will continue to appear every time the folder is clicked on until it is refreshed (either from a browser refresh - F5, or from hitting the kloudspeaker refresh).

Thanks!

**Comment by sjarvela** [comment] 2016-06-01 06:52
Which version are you using? Similar case was fixed in 2.7.17, and cannot reproduce this error in latest 2.7.18.

**Comment by snapgt** [comment] 2016-06-02 02:51
Apologies.  This was on 2.7.16 (rev44).  I did not realize you roll out
releases so quickly.  I'll upgrade tonight.  Thanks for the response!

**Closed as completed** 2016-06-07 06:24 UTC
